# Generated by Django 5.1.3 on 2024-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_session_feedback_alter_session_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'CBT Session', 'verbose_name_plural': 'CBT Sessions'},
        ),
        migrations.AlterField(
            model_name='session',
            name='exercise',
            field=models.TextField(),
        ),
    ]
