# Generated by Django 5.1.3 on 2024-12-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_goal_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
